# Generated by Django 2.2.5 on 2019-11-26 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rabbit', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscribing', to=settings.AUTH_USER_MODEL)),
                ('suscribing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscriber', to='rabbit.Warren')),
            ],
            options={
                'unique_together': {('suscribing', 'suscriber')},
            },
        ),
    ]
