# Generated by Django 2.2.5 on 2019-11-30 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rabbit', '0005_suscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscribe',
            new_name='Subscribe',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='suscriber',
            new_name='subscriber',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='suscribing',
            new_name='subscribing',
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('subscribing', 'subscriber')},
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BinaryField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rabbit.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
