# Generated by Django 2.2.5 on 2019-11-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0006_auto_20191130_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rabbit.Comment'),
        ),
    ]
