# Generated by Django 2.2.5 on 2019-11-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0008_auto_20191130_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='value',
        ),
    ]
