# Generated by Django 2.2.5 on 2019-10-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rabbit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warren',
            fields=[
                ('name', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('profile_img', models.ImageField(null=True, upload_to=rabbit.models.get_image_filename_warren)),
                ('landscape_img', models.ImageField(null=True, upload_to=rabbit.models.get_image_filename_warren)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(null=True)),
                ('img', models.ImageField(null=True, upload_to=rabbit.models.get_image_filename_post)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warren', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rabbit.Warren')),
            ],
        ),
    ]
