# Generated by Django 2.2.6 on 2019-10-11 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rabbit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rabbit.Post')),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            bases=('rabbit.post',),
        ),
        migrations.CreateModel(
            name='ImgPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rabbit.Post')),
                ('img', models.ImageField(upload_to=rabbit.models.get_image_filename)),
            ],
            bases=('rabbit.post',),
        ),
        migrations.CreateModel(
            name='LinkPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rabbit.Post')),
                ('link', models.URLField()),
            ],
            bases=('rabbit.post',),
        ),
    ]
